version: "3.6"

services:
  frontend:
    build:
      dockerfile: ../dockerfiles/deploy/frontend
      context: ./web-client
      args:
        version: ${VERSION}
        NODE_VERSION: $NODE_VERSION
    environment:
      - BACKEND_URL=http://backend:8080 # Internal Docker Backend

  backend:
    build:
      dockerfile: ../dockerfiles/deploy/backend
      context: ./backend
      args:
        version: ${VERSION}
        GO_VERSION: $GO_VERSION
    volumes:
      - "./data/backend:/srv/scores"
    command:
      - "-connection"
      - "postgres://postgres:test@db?sslmode=disable"
      - "-provider"
      - "postgres"
      - "-gauth"
      - "/srv/scores/client_secret.json"
    environment:
      - GIN_MODE=release
      - BACKEND_URL=https://localhost
      - APP_ENV=production

  envoy:
    build:
      dockerfile: ./dockerfiles/deploy/envoy.test
      context: .
      args:
        ENVOY_VERSION: $ENVOY_VERSION
    volumes:
      - "./certs:/usr/share/letsencrypt/scores.network"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8001:8001"

  db:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.at
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "127.0.0.1:81:80"

  elasticsearch:
    build:
      dockerfile: "./dockerfiles/deploy/elasticsearch"
      context: .
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    build:
      dockerfile: "./dockerfiles/deploy/kibana"
      context: .
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    build:
      dockerfile: "./dockerfiles/deploy/logstash"
      context: .
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
